### ISSUE TITLE
Steps needed

### ISSUE THREAD

**Issue by thesemicolonjarvis** [varunotelli/E-commerce#1]
cannot import login and logout. Please write the steps to install your project and run it

**Comment by vecca26** [comment]
Please mention the steps to run this code

**Comment by varunotelli** [comment]
This issue has been resolved.

**Comment by vecca26** [comment]
still getting error in login and logout

**Comment by varunotelli** [comment]
Fixed.

**Comment by Aish-Raj-21** [comment]
How to run this on ubuntu?
